# These are supported funding model platforms

# github: [your-github-username]
# patreon: your-patreon-username
# open_collective: your-collective
# ko_fi: your-kofi-username
# custom: ['https://your-website.com']

